openerp init-script - start openerp as openerp user

diff --git a/files/etc/init.d/openerp-multi-instances-6 b/files/etc/init.d/openerp-multi-instances-6
--- a/files/etc/init.d/openerp-multi-instances-6
+++ b/files/etc/init.d/openerp-multi-instances-6
@@ -42,7 +42,7 @@ openerp() {
   
   for srv in $p; do
     if [ -L $srv ]; then
-      $srv $1 || echo "ERROR: unable to start $srv";
+      su -c "$srv $1" openerp || echo "ERROR: unable to start $srv";
     else
       echo "  $srv seems to be broken"
       exit 1
